import { Activity, CircleAlert, Clock3, ExternalLink, History, Link2, RadioTower, RefreshCw } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { useAssetConnectivity, useAssetMeasurements } from "../../../hooks/useAssets";
import { type SSEConnectionState, useSSE } from "../../../hooks/useSSE";
import { monitorAssetMeasurements } from "../../../services/asset.service";
import type { Asset, AssetMeasurementReading } from "../../../types/asset";

type DetailTab = "overview" | "measurements" | "connectivity";
const displayTime = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "medium" }).format(new Date(value)) : "No sample";
const displayValue = (reading: AssetMeasurementReading) => reading.value === null ? "—" : typeof reading.value === "number" ? reading.value.toLocaleString(undefined, { maximumFractionDigits: reading.semantic.precision }) : String(reading.value);

function AssetDetailPanel({ asset, initialTab = "overview" }: { asset: Asset; initialTab?: DetailTab }) {
  const snapshot = useAssetMeasurements(asset.id);
  const connectivity = useAssetConnectivity(asset.id);
  const [tab, setTab] = useState<DetailTab>(initialTab);
  const [state, setState] = useState<SSEConnectionState>("idle");
  const [streamError, setStreamError] = useState<string | null>(null);
  const [restartKey, setRestartKey] = useState(0);
  const [live, setLive] = useState<Record<string, AssetMeasurementReading>>({});
  const latestSequence = useMemo(() => Math.max(0, ...Object.values(live).map((value) => value.sequence ?? 0), ...(snapshot.data?.measurements.map((value) => value.latest.sequence ?? 0) ?? [])), [live, snapshot.data]);
  const open = useCallback((context: Parameters<typeof monitorAssetMeasurements>[1]) => monitorAssetMeasurements(asset.id, context), [asset.id]);
  useSSE({ enabled: Boolean(snapshot.data), restartKey, getLastEventId: () => latestSequence || null, open, onMessage: (reading) => { setLive((current) => ({ ...current, [reading.binding_id]: reading })); setStreamError(null); }, onStateChange: setState, onError: (error) => setStreamError(error instanceof Error ? error.message : "Measurement stream unavailable") });
  const measurements = snapshot.data?.measurements ?? [];

  return <div className="asset-detail">
    <nav className="asset-detail-tabs" aria-label="Asset detail views"><button className={tab === "overview" ? "is-active" : ""} onClick={() => setTab("overview")}>Overview</button><button className={tab === "measurements" ? "is-active" : ""} onClick={() => setTab("measurements")}>Measurements <span>{measurements.length}</span></button><button className={tab === "connectivity" ? "is-active" : ""} onClick={() => setTab("connectivity")}>Connectivity</button></nav>
    {tab === "overview" && <section className="asset-detail-overview"><p className="asset-eyebrow">Selected {asset.kind}</p><h2>{asset.name}</h2><p>{asset.description ?? "No description has been added for this asset."}</p><dl><div><dt>State</dt><dd><span className={asset.enabled ? "asset-state is-enabled" : "asset-state"}>{asset.enabled ? "Enabled" : "Disabled"}</span></dd></div><div><dt>Timezone</dt><dd>{asset.timezone ?? "Inherited"}</dd></div><div><dt>Live stream</dt><dd><span className={`asset-stream is-${state}`}><i />{state}</span>{state === "disconnected" && <button type="button" title={streamError ?? undefined} onClick={() => setRestartKey((value) => value + 1)}><RefreshCw size={14} />Reconnect</button>}</dd></div><div><dt>Captured</dt><dd>{displayTime(snapshot.data?.captured_at)}</dd></div></dl>{streamError && <div className="asset-detail-warning" role="status"><CircleAlert size={17} />Showing the last synchronized values while reconnecting.</div>}</section>}
    {tab === "measurements" && <section className="asset-measurements" aria-label="Live Asset measurements">{snapshot.isLoading && <p role="status">Loading measurements…</p>}{snapshot.isError && <p role="alert">Couldn’t load measurements.</p>}{!snapshot.isLoading && measurements.length === 0 && <div className="asset-detail-empty"><Activity /><strong>No measurements bound</strong><span>Add a Tag or Plugin-output binding in the workspace.</span></div>}{measurements.map((projection) => { const reading = live[projection.binding.id] ?? projection.latest; const stale = state !== "live" && reading.available; const history = [reading, ...projection.history.filter((item) => item.sequence !== reading.sequence)].slice(0, 10); const sourcePath = reading.source.kind === "tag" ? `/tags/${encodeURIComponent(reading.source.tag_id)}` : `/plugins/${encodeURIComponent(reading.source.plugin_instance_id)}/energy/history`; return <article className={stale ? "asset-measurement is-stale" : "asset-measurement"} key={projection.binding.id}><header><div><span>{reading.semantic.resource} / {reading.semantic.quantity}</span><strong>{displayValue(reading)} <small>{reading.semantic.unit}</small></strong></div><span className={`asset-quality is-${reading.available ? reading.quality : "unavailable"}`}><i />{stale ? "stale" : reading.available ? reading.quality : "unavailable"}</span></header>{reading.error && <p className="asset-reading-error">{reading.error}</p>}<div className="asset-reading-meta"><span><Clock3 size={14} />{displayTime(reading.observed_at ?? reading.emitted_at)}</span><Link to={sourcePath}><ExternalLink size={14} />Open {reading.source.kind === "tag" ? "Tag history" : "Plugin history"}</Link></div><details><summary><History size={15} />History · {projection.history_retention === "runtime_memory" ? `latest ${history.length} runtime samples` : "latest Plugin output only"}</summary><ol>{history.map((item, index) => <li key={`${item.sequence ?? 0}-${index}`}><time>{displayTime(item.observed_at ?? item.emitted_at)}</time><strong>{displayValue(item)} {item.semantic.unit}</strong><span>{item.quality}</span></li>)}</ol></details></article>; })}</section>}
    {tab === "connectivity" && <section className="asset-connectivity" aria-label="Asset connectivity">{connectivity.isLoading && <p role="status">Loading connectivity…</p>}{connectivity.isError && <p role="alert">Couldn’t load connectivity.</p>}{connectivity.data?.links.length === 0 && <div className="asset-detail-empty"><Link2 /><strong>No connectivity links</strong><span>Plugin sources and unbound Assets may not have a physical chain.</span></div>}{connectivity.data?.links.map((link) => <article key={link.binding_id}><header><RadioTower /><span>{link.source.kind === "tag" ? "Tag acquisition path" : "Plugin output"}</span></header><ol>{[link.tag, link.datasource, link.device, link.vgateway].filter(Boolean).map((entity) => { const value = entity!; const target = value.kind === "tag" ? `/tags/${encodeURIComponent(value.id)}?asset=${encodeURIComponent(asset.id)}` : value.kind === "vgateway" ? `/vgateways/${encodeURIComponent(value.id)}` : `/devices?search=${encodeURIComponent(value.name)}`; return <li key={value.id}><span>{value.kind}</span><Link to={target}>{value.name}</Link><small>{value.enabled ? "Enabled" : "Disabled"}</small></li>; })}</ol>{link.source.kind === "plugin_output" && <Link to={`/plugins/${encodeURIComponent(link.source.plugin_instance_id)}/energy/history`}><code>{link.source.output_key}</code></Link>}</article>)}</section>}
  </div>;
}

export default AssetDetailPanel;
