import { CircleAlert, DatabaseZap, Gauge, GitBranch, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { listAssets } from "../../../services/asset.service";
import { getDataLogger, listDataLoggers } from "../../../services/datalogger.service";
import type { Asset } from "../../../types/asset";
import type { DataLogger, DataLoggerTagReference } from "../../../types/datalogger";
import "../../plugin/pages/EnergyWizardPage.css";
import { utilityQuantities as quantities, utilityUnits as units, validateUtilityDraft, type Resource, type SourceKind, type UtilityDraft } from "./utilityMapping";

function UtilityMappingPage() {
  const [assets, setAssets] = useState<Asset[]>([]); const [loggers, setLoggers] = useState<DataLogger[]>([]); const [tags, setTags] = useState<DataLoggerTagReference[]>([]);
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [reviewed, setReviewed] = useState(false);
  const [draft, setDraft] = useState<UtilityDraft>({ assetID: "", loggerID: "", resource: "electricity", sourceKind: "tag", sourceID: "", quantity: "power", unit: "kW", tariffMode: "none", currency: "THB", rate: 0 });
  useEffect(() => { const controller = new AbortController(); void Promise.all([listAssets({ page: 1, per_page: 100 }, controller.signal), listDataLoggers({ page: 1, per_page: 100 }, controller.signal)]).then(([assetResponse, loggerResponse]) => { setAssets(assetResponse.data); setLoggers(loggerResponse.data); setLoading(false); }).catch(() => { if (!controller.signal.aborted) { setLoadError("Couldn’t load Assets and Data Loggers. Check the API connection and try again."); setLoading(false); } }); return () => controller.abort(); }, []);
  useEffect(() => { if (!draft.loggerID) return; const controller = new AbortController(); void getDataLogger(draft.loggerID, controller.signal).then((logger) => setTags(logger.tags ?? [])).catch(() => { if (!controller.signal.aborted) setTags([]); }); return () => controller.abort(); }, [draft.loggerID]);
  const errors = useMemo(() => validateUtilityDraft(draft), [draft]);
  const update = <K extends keyof UtilityDraft>(key: K, value: UtilityDraft[K]) => { setDraft((current) => ({ ...current, [key]: value })); setReviewed(false); };
  const chooseResource = (resource: Resource) => setDraft((current) => ({ ...current, resource, quantity: quantities[resource][0], unit: units[resource][0] }));
  return <main className="energy-wizard"><header className="energy-wizard-header"><div><p className="energy-eyebrow">Utilities · semantic mapping</p><h1>Describe what each source measures</h1><p>Connect synchronized history to an Asset using plant terminology. The backend will validate ownership, units and source compatibility again before enablement.</p></div><Link to="/plugins">Cancel</Link></header>
    {loading && <p role="status">Loading configuration choices…</p>}{loadError && <div className="energy-guidance" role="alert"><CircleAlert />{loadError}</div>}
    {!loading && !loadError && <><section className="energy-panel"><div className="energy-panel-heading"><GitBranch /><div><h2>1. Choose the utility boundary</h2><p>The Asset determines where totals and downstream rollups belong.</p></div></div><div className="energy-form-grid"><label><span>Resource template</span><select aria-label="Resource template" value={draft.resource} onChange={(event) => chooseResource(event.target.value as Resource)}><option value="electricity">Electricity</option><option value="thermal">Thermal energy</option><option value="compressed_air">Compressed air</option><option value="water">Water</option></select></label><label><span>Asset</span><select aria-label="Asset" value={draft.assetID} onChange={(event) => update("assetID", event.target.value)}><option value="">Choose Asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.name} · {asset.kind}</option>)}</select></label></div></section>
      <section className="energy-panel"><div className="energy-panel-heading"><DatabaseZap /><div><h2>2. Select synchronized history</h2><p>Choose one Logger, then map a Tag or a reusable Plugin output.</p></div></div><div className="energy-form-grid"><label><span>Data Logger</span><select aria-label="Data Logger" value={draft.loggerID} onChange={(event) => { update("loggerID", event.target.value); update("sourceID", ""); }}><option value="">Choose Data Logger</option>{loggers.map((logger) => <option key={logger.id} value={logger.id}>{logger.name}</option>)}</select></label><label><span>Source type</span><select aria-label="Source type" value={draft.sourceKind} onChange={(event) => { update("sourceKind", event.target.value as SourceKind); update("sourceID", ""); }}><option value="tag">Logger Tag</option><option value="plugin_output">Plugin output</option></select></label>{draft.sourceKind === "tag" ? <label><span>Logger Tag</span><select aria-label="Logger Tag" value={draft.sourceID} onChange={(event) => update("sourceID", event.target.value)}><option value="">Choose Tag</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name} · {tag.data_type}</option>)}</select></label> : <label><span>Plugin output key</span><input aria-label="Plugin output key" placeholder="compressed_air.energy" value={draft.sourceID} onChange={(event) => update("sourceID", event.target.value)} /></label>}</div></section>
      <section className="energy-panel"><div className="energy-panel-heading"><Gauge /><div><h2>3. Confirm measurement meaning</h2><p>Meaning and unit must agree; incompatible combinations are blocked before review.</p></div></div><div className="energy-form-grid"><label><span>Measurement</span><select aria-label="Measurement" value={draft.quantity} onChange={(event) => update("quantity", event.target.value)}>{quantities[draft.resource].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Unit</span><select aria-label="Unit" value={draft.unit} onChange={(event) => update("unit", event.target.value)}>{units[draft.resource].map((value) => <option key={value}>{value}</option>)}</select></label></div></section>
      <section className="energy-panel"><div className="energy-panel-heading"><WalletCards /><div><h2>4. Tariff</h2><p>Leave cost disabled, enter a fixed rate, or map a synchronized rate source later.</p></div></div><div className="energy-form-grid"><label><span>Tariff</span><select aria-label="Tariff" value={draft.tariffMode} onChange={(event) => update("tariffMode", event.target.value as UtilityDraft["tariffMode"])}><option value="none">No cost calculation</option><option value="fixed">Fixed rate</option><option value="source">Synchronized source</option></select></label>{draft.tariffMode !== "none" && <label><span>Currency</span><input aria-label="Currency" maxLength={3} value={draft.currency} onChange={(event) => update("currency", event.target.value.toUpperCase())} /></label>}{draft.tariffMode === "fixed" && <label><span>Rate per energy unit</span><input aria-label="Rate per energy unit" type="number" min="0" value={draft.rate} onChange={(event) => update("rate", Number(event.target.value))} /></label>}</div></section>
      {errors.length > 0 && <div className="energy-guidance" role="alert"><CircleAlert /><div><strong>Complete these choices</strong><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div></div>}
      <footer className="energy-wizard-actions"><button type="button" disabled={errors.length > 0} onClick={() => setReviewed(true)}>Review mapping</button></footer>
      {reviewed && <section className="energy-panel" aria-label="Mapping review"><div className="energy-panel-heading"><Gauge /><div><h2>Ready for backend validation</h2><p>{assets.find((asset) => asset.id === draft.assetID)?.name}: {draft.resource} {draft.quantity} from {draft.sourceKind === "tag" ? tags.find((tag) => tag.id === draft.sourceID)?.name : draft.sourceID}, recorded as {draft.unit}.</p></div></div><p>This foundation previews the contract only. It does not enable a calculation or change acquisition timing.</p></section>}
    </>}
  </main>;
}
export default UtilityMappingPage;
