import { CircleAlert, DatabaseZap, Gauge, GitBranch, WalletCards } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";

import { listAssets } from "../../../services/asset.service";
import { getDataLogger, listDataLoggers } from "../../../services/datalogger.service";
import type { Asset } from "../../../types/asset";
import type { DataLogger, DataLoggerTagReference } from "../../../types/datalogger";
import "../../plugin/pages/EnergyWizardPage.css";
import { buildCalculationPreview, utilityQuantities as quantities, utilityUnits as units, validateUtilityDraft, type Resource, type SourceKind, type UtilityDraft } from "./utilityMapping";

function UtilityMappingPage() {
  const [assets, setAssets] = useState<Asset[]>([]); const [loggers, setLoggers] = useState<DataLogger[]>([]); const [tags, setTags] = useState<DataLoggerTagReference[]>([]);
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [reviewed, setReviewed] = useState(false);
  const [draft, setDraft] = useState<UtilityDraft>({ assetID: "", loggerID: "", resource: "electricity", sourceKind: "tag", sourceID: "", quantity: "power", unit: "kW", tariffMode: "none", currency: "THB", rate: 0, flowBasis: "normalized", referenceTemperatureKelvin: 293.15, referencePressurePascal: 101325, pressureBasis: "gauge", baselineBasis: "no_production" });
  useEffect(() => { const controller = new AbortController(); void Promise.all([listAssets({ page: 1, per_page: 100 }, controller.signal), listDataLoggers({ page: 1, per_page: 100 }, controller.signal)]).then(([assetResponse, loggerResponse]) => { setAssets(assetResponse.data); setLoggers(loggerResponse.data); setLoading(false); }).catch(() => { if (!controller.signal.aborted) { setLoadError("Couldn’t load Assets and Data Loggers. Check the API connection and try again."); setLoading(false); } }); return () => controller.abort(); }, []);
  useEffect(() => { if (!draft.loggerID) return; const controller = new AbortController(); void getDataLogger(draft.loggerID, controller.signal).then((logger) => setTags(logger.tags ?? [])).catch(() => { if (!controller.signal.aborted) setTags([]); }); return () => controller.abort(); }, [draft.loggerID]);
  const errors = useMemo(() => validateUtilityDraft(draft), [draft]);
  const preview = useMemo(() => buildCalculationPreview(draft), [draft]);
  const update = <K extends keyof UtilityDraft>(key: K, value: UtilityDraft[K]) => { setDraft((current) => ({ ...current, [key]: value })); setReviewed(false); };
  const chooseResource = (resource: Resource) => setDraft((current) => ({ ...current, resource, quantity: quantities[resource][0], unit: units[resource][0] }));
  return <main className="energy-wizard"><header className="energy-wizard-header"><div><p className="energy-eyebrow">Utilities · semantic mapping</p><h1>Describe what each source measures</h1><p>Connect synchronized history to an Asset using plant terminology. The backend will validate ownership, units and source compatibility again before enablement.</p></div><Link to="/plugins">Cancel</Link></header>
    {loading && <p role="status">Loading configuration choices…</p>}{loadError && <div className="energy-guidance" role="alert"><CircleAlert />{loadError}</div>}
    {!loading && !loadError && <><section className="energy-panel"><div className="energy-panel-heading"><GitBranch /><div><h2>1. Choose the utility boundary</h2><p>The Asset determines where totals and downstream rollups belong.</p></div></div><div className="energy-form-grid"><label><span>Resource template</span><select aria-label="Resource template" value={draft.resource} onChange={(event) => chooseResource(event.target.value as Resource)}><option value="electricity">Electricity</option><option value="thermal">Thermal energy</option><option value="compressed_air">Compressed air</option><option value="water">Water</option></select></label><label><span>Asset</span><select aria-label="Asset" value={draft.assetID} onChange={(event) => update("assetID", event.target.value)}><option value="">Choose Asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.name} · {asset.kind}</option>)}</select></label></div></section>
      <section className="energy-panel"><div className="energy-panel-heading"><DatabaseZap /><div><h2>2. Select synchronized history</h2><p>Choose one Logger, then map a Tag or a reusable Plugin output.</p></div></div><div className="energy-form-grid"><label><span>Data Logger</span><select aria-label="Data Logger" value={draft.loggerID} onChange={(event) => { update("loggerID", event.target.value); update("sourceID", ""); }}><option value="">Choose Data Logger</option>{loggers.map((logger) => <option key={logger.id} value={logger.id}>{logger.name}</option>)}</select></label><label><span>Source type</span><select aria-label="Source type" value={draft.sourceKind} onChange={(event) => { update("sourceKind", event.target.value as SourceKind); update("sourceID", ""); }}><option value="tag">Logger Tag</option><option value="plugin_output">Plugin output</option></select></label>{draft.sourceKind === "tag" ? <label><span>Logger Tag</span><select aria-label="Logger Tag" value={draft.sourceID} onChange={(event) => update("sourceID", event.target.value)}><option value="">Choose Tag</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name} · {tag.data_type}</option>)}</select></label> : <label><span>Plugin output key</span><input aria-label="Plugin output key" placeholder="compressed_air.energy" value={draft.sourceID} onChange={(event) => update("sourceID", event.target.value)} /></label>}</div></section>
      <section className="energy-panel"><div className="energy-panel-heading"><Gauge /><div><h2>3. Confirm measurement meaning</h2><p>Meaning and unit must agree; incompatible combinations are blocked before review.</p></div></div><div className="energy-form-grid"><label><span>Measurement</span><select aria-label="Measurement" value={draft.quantity} onChange={(event) => update("quantity", event.target.value)}>{quantities[draft.resource].map((value) => <option key={value}>{value}</option>)}</select></label><label><span>Unit</span><select aria-label="Unit" value={draft.unit} onChange={(event) => update("unit", event.target.value)}>{units[draft.resource].map((value) => <option key={value}>{value}</option>)}</select></label></div></section>
      {draft.resource === "compressed_air" && <section className="energy-panel"><div className="energy-panel-heading"><Gauge /><div><h2>Compressed-air conditions and states</h2><p>Reference conditions prevent actual and normalized volume from being mixed. State Tags and baseline selection remain explicit.</p></div></div><div className="energy-form-grid"><label><span>Compressor power Tag</span><select aria-label="Compressor power Tag" value={draft.compressorPowerSource ?? ""} onChange={(event) => update("compressorPowerSource", event.target.value)}><option value="">Choose power Tag</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label><label><span>Air volume basis</span><select aria-label="Air volume basis" value={draft.flowBasis} onChange={(event) => update("flowBasis", event.target.value as "actual" | "normalized")}><option value="normalized">Normalized volume (Nm³)</option><option value="actual">Actual volume (m³)</option></select></label>{draft.flowBasis === "normalized" && <><label><span>Reference temperature (K)</span><input aria-label="Reference temperature" type="number" min="0.01" step="0.01" value={draft.referenceTemperatureKelvin} onChange={(event) => update("referenceTemperatureKelvin", Number(event.target.value))} /></label><label><span>Reference pressure (Pa absolute)</span><input aria-label="Reference pressure" type="number" min="1" step="1" value={draft.referencePressurePascal} onChange={(event) => update("referencePressurePascal", Number(event.target.value))} /></label></>}<label><span>Pressure reading type</span><select aria-label="Pressure reading type" value={draft.pressureBasis} onChange={(event) => update("pressureBasis", event.target.value as "gauge" | "absolute")}><option value="gauge">Gauge pressure</option><option value="absolute">Absolute pressure</option></select></label><label><span>Operating-state Tag (optional)</span><select aria-label="Operating-state Tag" value={draft.operatingStateSource ?? ""} onChange={(event) => update("operatingStateSource", event.target.value)}><option value="">Not mapped</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label><label><span>Production-state Tag (optional)</span><select aria-label="Production-state Tag" value={draft.productionStateSource ?? ""} onChange={(event) => update("productionStateSource", event.target.value)}><option value="">Not mapped</option>{tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</select></label><label><span>Baseline evidence</span><select aria-label="Baseline evidence" value={draft.baselineBasis} onChange={(event) => update("baselineBasis", event.target.value as "idle" | "no_production")}><option value="no_production">Confirmed no-production period</option><option value="idle">Confirmed idle period</option></select><small>This labels an estimate; it does not automatically diagnose a leak.</small></label></div></section>}
      <section className="energy-panel"><div className="energy-panel-heading"><WalletCards /><div><h2>4. Tariff</h2><p>Leave cost disabled, enter a fixed rate, or map a synchronized rate source later.</p></div></div><div className="energy-form-grid"><label><span>Tariff</span><select aria-label="Tariff" value={draft.tariffMode} onChange={(event) => update("tariffMode", event.target.value as UtilityDraft["tariffMode"])}><option value="none">No cost calculation</option><option value="fixed">Fixed rate</option><option value="source">Synchronized source</option></select></label>{draft.tariffMode !== "none" && <label><span>Currency</span><input aria-label="Currency" maxLength={3} value={draft.currency} onChange={(event) => update("currency", event.target.value.toUpperCase())} /></label>}{draft.tariffMode === "fixed" && <label><span>Rate per energy unit</span><input aria-label="Rate per energy unit" type="number" min="0" value={draft.rate} onChange={(event) => update("rate", Number(event.target.value))} /></label>}</div></section>
      <section className="energy-panel" aria-label="Calculation preview"><div className="energy-panel-heading"><Gauge /><div><h2>Calculation preview and provenance</h2><p>Review this contract before enabling. No result is estimated from missing history.</p></div></div><div className="energy-review-grid"><article className="is-wide"><span>Formula</span><strong>{preview.formula}</strong></article><article className="is-wide"><span>Source period</span><strong>{preview.sourcePeriod}</strong></article><article><span>Coverage</span><strong>{preview.coverage}</strong></article><article><span>Unit conversion</span><strong>{preview.unitConversion}</strong></article><article className="is-wide"><span>Missing inputs</span><strong>{preview.missingInputs.length ? preview.missingInputs.join(" ") : "None in this draft"}</strong></article><article className="is-wide"><span>Fail-closed status</span><strong>{preview.failClosedReason ?? "Draft is complete; backend source validation is still required"}</strong></article></div></section>
      {errors.length > 0 && <div className="energy-guidance" role="alert"><CircleAlert /><div><strong>Complete these choices</strong><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div></div>}
      <footer className="energy-wizard-actions"><button type="button" disabled={errors.length > 0} onClick={() => setReviewed(true)}>Review mapping</button></footer>
      {reviewed && <section className="energy-panel" aria-label="Mapping review"><div className="energy-panel-heading"><Gauge /><div><h2>Ready for backend validation</h2><p>{assets.find((asset) => asset.id === draft.assetID)?.name}: {draft.resource} {draft.quantity} from {draft.sourceKind === "tag" ? tags.find((tag) => tag.id === draft.sourceID)?.name : draft.sourceID}, recorded as {draft.unit}.</p>{draft.resource === "compressed_air" && <p>{draft.flowBasis === "normalized" ? `Normalized at ${draft.referenceTemperatureKelvin} K and ${draft.referencePressurePascal} Pa absolute` : "Actual volume"}; pressure is {draft.pressureBasis}; baseline evidence is {draft.baselineBasis?.replace("_", " ")}.</p>}</div></div><p>This foundation previews the contract only. It does not enable a calculation, diagnose leakage, or change acquisition timing.</p></section>}
    </>}
  </main>;
}
export default UtilityMappingPage;
